const ActionTypes = {
  GENRE_LOADING: "GENRE_LOADING",
  GENRE_ERROR: "GENRE_ERROR",
  GENRE_SUCCESS: "GENRE_SUCCESS",

  MOVIE_LOADING: "MOVIE_LOADING",
  MOVIE_SUCCESS: "MOVIE_SUCCESS",
  MOVIE_ERROR: "MOVIE_ERROR",
  MOVIE_ADD: "MOVIE_ADD",
  MOVIE_DELETE: "MOVIE_DELETE",
};

export default ActionTypes;
